In [1]:
import numpy as np

In [4]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
myarray = np.array(mylist)

In [7]:
type(myarray)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [23]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(1)

array([0.41186894])

In [26]:
np.random.rand(5,6)

array([[0.3446651 , 0.07555385, 0.26418673, 0.57565776, 0.58831294,
        0.43116017],
       [0.26583227, 0.013881  , 0.32605056, 0.05001046, 0.61455481,
        0.51511303],
       [0.36618459, 0.10988746, 0.55126015, 0.36854053, 0.79714935,
        0.77612674],
       [0.40608537, 0.93882547, 0.19522533, 0.68241225, 0.84312596,
        0.70702734],
       [0.60038085, 0.88231272, 0.03089525, 0.25305014, 0.70369855,
        0.77785397]])

In [27]:
np.random.rand(5,2)

array([[0.33686284, 0.96587602],
       [0.08921308, 0.72368912],
       [0.28369968, 0.57822081],
       [0.98842748, 0.83260123],
       [0.95542769, 0.01952417]])

In [28]:
np.random.randn(10)

array([ 0.21868253, -0.39383992,  0.85497988,  1.74888543, -1.41989805,
        0.37213475, -0.31005259,  0.33630095, -1.22287991,  2.00734321])

In [29]:
np.random.randn(2,3)

array([[ 0.02622917,  0.37600055,  0.43364376],
       [-1.22613323, -0.67927668,  0.56478642]])

In [30]:
np.random.randint(0,101,5)

array([47, 71, 13, 35, 44])

In [31]:
np.random.randint(0,101,(4,5))

array([[ 24,  43, 100, 100,  56],
       [ 54,  16,  41,  65,  73],
       [  3,  47,  68,  87,   5],
       [ 90,  51,  13,  10,  68]])

In [32]:
np.random.seed(42)

In [33]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr = np.random.randint(0,101,10)

In [38]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [39]:
ranarr.max()

99

In [40]:
ranarr.min()

2

In [41]:
ranarr.argmax()

5

In [42]:
ranarr.argmin()

7

In [44]:
ranarr.dtype

dtype('int32')

In [45]:
ranarr.shape

(10,)

In [46]:
arr.shape

(25,)

In [47]:
arr = arr.reshape(5,5)

In [48]:
arr.shape

(5, 5)