In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [3]:
myarray = np.array(mylist)

In [4]:
type(myarray)

numpy.ndarray

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [19]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(1)

array([0.61621276])

In [22]:
np.random.rand(5,6)

array([[0.73817022, 0.04347112, 0.09107695, 0.23816517, 0.78124375,
        0.55214851],
       [0.81889807, 0.88100363, 0.90685296, 0.49772747, 0.53507108,
        0.62588164],
       [0.16120115, 0.70471754, 0.98690799, 0.00543458, 0.0324178 ,
        0.26997025],
       [0.63070978, 0.81018545, 0.23379478, 0.88028931, 0.71754662,
        0.96126829],
       [0.85262239, 0.5981728 , 0.11347388, 0.33653907, 0.68536475,
        0.94221326]])

In [23]:
np.random.rand(5,2)

array([[0.29706416, 0.83069363],
       [0.9021362 , 0.51239942],
       [0.48834156, 0.22638804],
       [0.87711312, 0.20208822],
       [0.16738114, 0.98014815]])

In [24]:
np.random.randn(10)

array([ 1.03011182, -0.22831783,  0.27365409,  0.69542738,  0.51278214,
       -1.09175253,  0.07436515, -1.42061613, -0.40591392, -0.90432772])

In [25]:
np.random.randn(2,3)

array([[-0.00503177, -0.95238735, -0.53613249],
       [ 1.7770837 ,  2.55335494, -0.76480925]])

In [26]:
np.random.randint(0,101,5)

array([25, 71, 28, 87, 93])

In [27]:
np.random.randint(0,101,(4,5))

array([[33, 22, 95, 33, 37],
       [51, 51, 14, 47, 90],
       [ 2, 44, 22, 34, 50],
       [58, 55, 75, 73, 21]])

In [28]:
np.random.seed(42)

In [29]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr = np.random.randint(0,101,10)

In [34]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [35]:
ranarr.max()

99

In [36]:
ranarr.min()

2

In [37]:
ranarr.argmax()

5

In [38]:
ranarr.argmin()

7

In [39]:
ranarr.dtype

dtype('int32')

In [40]:
ranarr.shape

(10,)

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr = np.arange(0,11)

In [45]:
arr[8]

8

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[0:5] = 100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

In [51]:
arr_slice = arr[:6]

In [52]:
arr_slice

array([0, 1, 2, 3, 4, 5])

In [53]:
arr_slice[:] = 99

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
# Reset array
arr = np.arange(0,11)

In [56]:
arr_copy = arr.copy()

In [57]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr_copy[:6] = 99

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [62]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
arr_2d[1]

array([20, 25, 30])

In [64]:
arr_2d[1,1]

25

In [65]:
arr = np.arange(0, 10)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [69]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
arr / arr

<ipython-input-71-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
1 / arr

<ipython-input-72-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [75]:
np.log(arr)

<ipython-input-75-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr.sum()

45

In [79]:
arr.mean()

4.5

In [80]:
arr.max()

9

In [81]:
arr.var()

8.25

In [82]:
arr.std()

2.8722813232690143

In [83]:
arr_2dim = np.arange(0,25).reshape(5,5)

In [84]:
arr_2dim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
arr_2dim.sum()

300

In [86]:
arr_2dim.sum(axis=0)

array([50, 55, 60, 65, 70])

In [87]:
arr_2dim.sum(axis=1)

array([ 10,  35,  60,  85, 110])